version: "3"
services:
    notebook:
        image: notebook
        volumes:
            - ./notebook:/home/jovyan/work
        ports:
            - 8888:8888

    datasette:
        image: datasette
        volumes:
            - ./notebook/database:/work
        ports:
            - 8001:8001
        command: serve "/work/corp data.db" --setting base_url /my-datasette/ -p 8001 -h 0.0.0.0

    pudl:
        image: datasette
        depends_on:
            - datasette
        volumes:
            - ./notebook/database:/work
        ports:
            - 8002:8002
        command: serve /work/pudl.sqlite --setting base_url /pudl-datasette/ -p 8002 -h 0.0.0.0

