version: "3"
services:
    notebook:
        image: notebook
        volumes:
            - ./notebook:/home/jovyan/work
        ports:
            - 8888:8888

    datasette:
        image: datasette
        volumes:
            - ./notebook/database:/work
        ports:
            - 8001:8001
